# Generated by Django 4.1.7 on 2023-03-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
